# example netlify.toml
[build]
  command = "vite build"
  functions = "netlify/functions"
  publish = "dist"

## Uncomment to use this redirect for Single Page Applications
## Not needed for static site generators.

  from = "/*"
  to = "/index.html"
  status = 200
